language: node_js
node_js:
  - "8"
script:
  npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  local-dir: build